version: '3.7'

services:
  kolyan-blog-api:
    image: ${REGISTRY}/freemoooont/kolyan-blog-api:master
    container_name: kolyan-blog-api
    restart: unless-stopped
    ports:
      - '80:3000'
    links:
      - mongo

  mongo:
    image: mongo:4.2.5
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=kolyanblog
      - MONGO_INITDB_DATABASE=kolyanblog
    ports:
      - '27017:27017'
    volumes:
      - ./addons/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db

volumes:
  dbdata:
